(() => {
  const $ = (id) => document.getElementById(id);
  const state = { page: 1, query: '', status: '', rows: [], loaded: false };
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api = async (path, options) => { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 20000); try { const response = await fetch(`/api/oshxona${path}`, { headers: {'Accept':'application/json','Content-Type':'application/json'}, signal: controller.signal, ...options }); if (!response.ok) throw new Error((await response.text()) || `HTTP ${response.status}`); return response.json(); } finally { clearTimeout(timer); } };
  const statusLabel = {published:'E’lon qilingan', review:'Tekshiruvda', draft:'Qoralama', archived:'Arxiv'};
  function render(rows) { $('names').innerHTML = rows.length ? rows.map((row) => `<tr><td><strong>${esc(row.name)}</strong><br><small>${esc(row.slug)}</small></td><td>${row.gender === 'm' ? 'O‘g‘il bola' : 'Qiz bola'}</td><td>${esc(row.origin || '—')}</td><td><span class="status ${esc(row.status)}">${statusLabel[row.status] || row.status}</span></td><td>${esc(row.updated_at || '—')}</td><td><button class="row-action" data-edit="${esc(row.id)}">Ochish</button></td></tr>`).join('') : '<tr><td colspan="6" class="empty">Yozuvlar topilmadi</td></tr>'; $('result-count').textContent = `${rows.length} ta yozuv`; }
  function fill(row = {}) { $('field-id').value = row.id || ''; $('field-name').value = row.name || ''; $('field-gender').value = row.gender || 'm'; $('field-status').value = row.status || 'draft'; $('field-meaning').value = row.meaning || ''; $('field-origin').value = row.origin || ''; $('field-variants').value = row.variants || ''; $('field-description').value = row.seo_description || ''; $('editor-title').textContent = row.id ? `Tahrirlash: ${row.name}` : 'Yangi ism'; $('form-status').textContent = ''; $('editor').showModal(); }
  async function importCatalog() {
    const button = $('import-names'); button.disabled = true; button.textContent = 'Import…'; let offset = 0; let total = 0;
    try { do { const data = await api(`/import?offset=${offset}&limit=200`, { method: 'POST' }); offset = data.nextOffset; total = data.total; button.textContent = `Import: ${Math.min(offset, total)} / ${total}`; } while (offset < total); await load(); button.textContent = 'Katalog import qilindi'; } catch (error) { button.textContent = 'Import xatosi'; $('result-count').textContent = error.message; } finally { button.disabled = false; }
  }
  async function load() { try { const data = await api(`/names-lite?q=${encodeURIComponent(state.query)}`); render(data.rows || []); const counts = data.counts || {}; $('stat-total').textContent = counts.total ?? '—'; $('stat-published').textContent = counts.published ?? '—'; $('stat-review').textContent = counts.review ?? '—'; $('stat-draft').textContent = counts.draft ?? '—'; state.rows = data.rows || []; state.loaded = true; $('user-email').textContent = data.user || 'Administrator'; } catch (error) { $('names').innerHTML = `<tr><td colspan="6" class="empty">Ma’lumotlarni yuklab bo‘lmadi: ${esc(error.message)}</td></tr>`; } }
  $('search').addEventListener('input', (event) => { state.query = event.target.value.trim(); load(); }); $('status').addEventListener('change', (event) => { state.status = event.target.value; load(); }); $('import-names').addEventListener('click', importCatalog); $('new-name').addEventListener('click', () => fill()); $('close-editor').addEventListener('click', () => $('editor').close()); $('cancel-editor').addEventListener('click', () => $('editor').close()); $('names').addEventListener('click', (event) => { const id = event.target.closest('[data-edit]')?.dataset.edit; if (id) fill(state.rows.find((row) => row.id === id)); }); $('name-form').addEventListener('submit', async (event) => { event.preventDefault(); const id = $('field-id').value; const payload = { name: $('field-name').value.trim(), gender: $('field-gender').value, status: $('field-status').value, meaning: $('field-meaning').value.trim(), origin: $('field-origin').value.trim(), variants: $('field-variants').value.trim(), seo_description: $('field-description').value.trim() }; try { await api(id ? `/names/${encodeURIComponent(id)}` : '/names', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); $('editor').close(); await load(); } catch (error) { $('form-status').textContent = error.message; } });
  const articleState = { rows: [], q: '', status: '' }; const articleLabel = {published:'E’lon qilingan', review:'Tekshiruvda', draft:'Qoralama', archived:'Arxiv'};
  function renderArticles(rows) { $('articles').innerHTML = rows.length ? rows.map((row) => `<tr><td><strong>${esc(row.title)}</strong><br><small>/maqolalar/${esc(row.slug)}/</small></td><td>${esc(row.category || '—')}</td><td><span class="status ${esc(row.status)}">${articleLabel[row.status] || row.status}</span></td><td>${esc(row.updated_at || '—')}</td><td><button class="row-action" data-article-edit="${esc(row.id)}">Ochish</button></td></tr>`).join('') : '<tr><td colspan="5" class="empty">Maqolalar topilmadi</td></tr>'; $('article-count').textContent = `${rows.length} ta maqola`; }
  function fillArticle(row = {}) { $('article-id').value = row.id || ''; $('article-title').value = row.title || ''; $('article-category').value = row.category || ''; $('article-state').value = row.status || 'draft'; $('article-cover-image').value = row.cover_image || ''; $('article-excerpt').value = row.excerpt || ''; $('article-content').value = row.content || ''; $('article-description').value = row.seo_description || ''; $('article-editor-title').textContent = row.id ? `Tahrirlash: ${row.title}` : 'Yangi maqola'; $('article-status-message').textContent = ''; $('article-editor').showModal(); }
  async function loadArticles() { try { const data = await api(`/articles?q=${encodeURIComponent(articleState.q)}&status=${encodeURIComponent(articleState.status)}`); articleState.rows = data.rows || []; renderArticles(articleState.rows); } catch (error) { $('articles').innerHTML = `<tr><td colspan="5" class="empty">${esc(error.message)}</td></tr>`; } }
  $('article-search').addEventListener('input', (event) => { articleState.q = event.target.value.trim(); loadArticles(); }); $('article-status').addEventListener('change', (event) => { articleState.status = event.target.value; loadArticles(); }); $('new-article').addEventListener('click', () => fillArticle()); $('close-article').addEventListener('click', () => $('article-editor').close()); $('cancel-article').addEventListener('click', () => $('article-editor').close()); $('articles').addEventListener('click', (event) => { const id = event.target.closest('[data-article-edit]')?.dataset.articleEdit; if (id) fillArticle(articleState.rows.find((row) => row.id === id)); }); $('article-form').addEventListener('submit', async (event) => { event.preventDefault(); const id = $('article-id').value; const title = $('article-title').value.trim(); const payload = { title, slug: title.toLowerCase().replace(/[^a-z0-9а-яё]+/gi, '-').replace(/^-|-$/g, ''), category: $('article-category').value.trim(), status: $('article-state').value, cover_image: $('article-cover-image').value.trim(), excerpt: $('article-excerpt').value.trim(), content: $('article-content').value.trim(), seo_description: $('article-description').value.trim() }; try { await api(id ? `/articles/${encodeURIComponent(id)}` : '/articles', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); $('article-editor').close(); await loadArticles(); } catch (error) { $('article-status-message').textContent = error.message; } });
  const videoState = { rows: [], q: '', status: '' }; const videoLabel = {published:'E’lon qilingan', draft:'Qoralama', archived:'Arxiv'};
  function renderVideos(rows) { $('videos').innerHTML = rows.length ? rows.map((row) => `<tr><td><strong>${esc(row.title)}</strong><br><small>youtube.com/watch?v=${esc(row.video_id)}</small></td><td><code>${esc(row.video_id)}</code></td><td><span class="status ${esc(row.status)}">${videoLabel[row.status] || row.status}</span></td><td>${esc(row.sort_order ?? 0)}</td><td><button class="row-action" data-video-edit="${esc(row.id)}">Ochish</button></td></tr>`).join('') : '<tr><td colspan="5" class="empty">Videolar topilmadi</td></tr>'; $('video-count').textContent = `${rows.length} ta video`; }
  function fillVideo(row = {}) { $('video-id').value = row.id || ''; $('video-title').value = row.title || ''; $('video-youtube-id').value = row.video_id || ''; $('video-state').value = row.status || 'draft'; $('video-order').value = row.sort_order ?? 0; $('video-description').value = row.description || ''; $('video-editor-title').textContent = row.id ? `Tahrirlash: ${row.title}` : 'Yangi video'; $('video-status-message').textContent = ''; $('video-editor').showModal(); }
  async function loadVideos() { try { const data = await api(`/videos?q=${encodeURIComponent(videoState.q)}&status=${encodeURIComponent(videoState.status)}`); videoState.rows = data.rows || []; renderVideos(videoState.rows); } catch (error) { $('videos').innerHTML = `<tr><td colspan="5" class="empty">${esc(error.message)}</td></tr>`; } }
  $('video-search').addEventListener('input', (event) => { videoState.q = event.target.value.trim(); loadVideos(); }); $('video-status').addEventListener('change', (event) => { videoState.status = event.target.value; loadVideos(); }); $('new-video').addEventListener('click', () => fillVideo()); $('close-video').addEventListener('click', () => $('video-editor').close()); $('cancel-video').addEventListener('click', () => $('video-editor').close()); $('videos').addEventListener('click', (event) => { const id = event.target.closest('[data-video-edit]')?.dataset.videoEdit; if (id) fillVideo(videoState.rows.find((row) => row.id === id)); }); $('video-form').addEventListener('submit', async (event) => { event.preventDefault(); const id = $('video-id').value; const payload = { title: $('video-title').value.trim(), video_id: $('video-youtube-id').value.trim(), status: $('video-state').value, sort_order: Number($('video-order').value || 0), description: $('video-description').value.trim() }; try { await api(id ? `/videos/${encodeURIComponent(id)}` : '/videos', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); $('video-editor').close(); await loadVideos(); } catch (error) { $('video-status-message').textContent = error.message; } });
  const views = ['dashboard-view','names-view','articles-view','videos-view'];
  function activateView(id) {
    views.forEach((viewId) => { const node = $(viewId); if (node) node.classList.toggle('view-hidden', viewId !== id); });
    document.querySelectorAll('[data-view]').forEach((button) => button.classList.toggle('active', button.dataset.view === id));
    if (id === 'names-view' && !state.loaded) load();
    if (id === 'articles-view') loadArticles();
    if (id === 'videos-view') loadVideos();
  }
  document.querySelectorAll('[data-view]').forEach((button) => button.addEventListener('click', () => activateView(button.dataset.view)));
  activateView('dashboard-view');
})();
