(() => {
  const $ = (id) => document.getElementById(id);
  const state = { page: 1, query: '', status: '', rows: [] };
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api = async (path, options) => { const response = await fetch(`/api/oshxona${path}`, { headers: {'Accept':'application/json','Content-Type':'application/json'}, ...options }); if (!response.ok) throw new Error((await response.text()) || `HTTP ${response.status}`); return response.json(); };
  const statusLabel = {published:'Опубликовано', review:'На проверке', draft:'Черновик', archived:'Архив'};
  function render(rows) { $('names').innerHTML = rows.length ? rows.map((row) => `<tr><td><strong>${esc(row.name)}</strong><br><small>${esc(row.slug)}</small></td><td>${row.gender === 'm' ? 'O‘g‘il bola' : 'Qiz bola'}</td><td>${esc(row.origin || '—')}</td><td><span class="status ${esc(row.status)}">${statusLabel[row.status] || row.status}</span></td><td>${esc(row.updated_at || '—')}</td><td><button class="row-action" data-edit="${esc(row.id)}">Открыть</button></td></tr>`).join('') : '<tr><td colspan="6" class="empty">Записей не найдено</td></tr>'; $('result-count').textContent = `${rows.length} записей`; }
  function fill(row = {}) { $('field-id').value = row.id || ''; $('field-name').value = row.name || ''; $('field-gender').value = row.gender || 'm'; $('field-status').value = row.status || 'draft'; $('field-meaning').value = row.meaning || ''; $('field-origin').value = row.origin || ''; $('field-variants').value = row.variants || ''; $('field-description').value = row.seo_description || ''; $('editor-title').textContent = row.id ? `Редактирование: ${row.name}` : 'Новое имя'; $('form-status').textContent = ''; $('editor').showModal(); }
  async function importCatalog() {
    const button = $('import-names'); button.disabled = true; button.textContent = 'Импорт…'; let offset = 0; let total = 0;
    try { do { const data = await api(`/import?offset=${offset}&limit=200`, { method: 'POST' }); offset = data.nextOffset; total = data.total; button.textContent = `Импорт: ${Math.min(offset, total)} / ${total}`; } while (offset < total); await load(); button.textContent = 'Каталог импортирован'; } catch (error) { button.textContent = 'Ошибка импорта'; $('result-count').textContent = error.message; } finally { button.disabled = false; }
  }
  async function load() { try { const data = await api(`/names?page=${state.page}&q=${encodeURIComponent(state.query)}&status=${encodeURIComponent(state.status)}`); render(data.rows || []); const counts = data.counts || {}; $('stat-total').textContent = counts.total ?? '—'; $('stat-published').textContent = counts.published ?? '—'; $('stat-review').textContent = counts.review ?? '—'; $('stat-draft').textContent = counts.draft ?? '—'; state.rows = data.rows || []; $('user-email').textContent = data.user || 'Администратор'; } catch (error) { $('names').innerHTML = `<tr><td colspan="6" class="empty">Не удалось загрузить данные: ${esc(error.message)}</td></tr>`; } }
  $('search').addEventListener('input', (event) => { state.query = event.target.value.trim(); load(); }); $('status').addEventListener('change', (event) => { state.status = event.target.value; load(); }); $('import-names').addEventListener('click', importCatalog); $('new-name').addEventListener('click', () => fill()); $('close-editor').addEventListener('click', () => $('editor').close()); $('cancel-editor').addEventListener('click', () => $('editor').close()); $('names').addEventListener('click', (event) => { const id = event.target.closest('[data-edit]')?.dataset.edit; if (id) fill(state.rows.find((row) => row.id === id)); }); $('name-form').addEventListener('submit', async (event) => { event.preventDefault(); const id = $('field-id').value; const payload = { name: $('field-name').value.trim(), gender: $('field-gender').value, status: $('field-status').value, meaning: $('field-meaning').value.trim(), origin: $('field-origin').value.trim(), variants: $('field-variants').value.trim(), seo_description: $('field-description').value.trim() }; try { await api(id ? `/names/${encodeURIComponent(id)}` : '/names', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); $('editor').close(); await load(); } catch (error) { $('form-status').textContent = error.message; } }); load();
})();
